/*
 * Created by Kristiyan Butev.
 * Copyright © 2019 Kristiyan Butev. All rights reserved.
 */
package automater.ui.view;

import automater.utilities.Callback;
import automater.utilities.TimeType;
import automater.utilities.TimeValue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jetbrains.annotations.NotNull;

/**
 *
 * @author Byti
 */
public class EditMacroActionWaitPanel extends javax.swing.JPanel {
    // UI callbacks
    public Callback<String> onWaitTimeCallback = Callback.createDoNothing();
    public Callback<TimeType> onTimeTypeCallback = Callback.createDoNothing();
    
    public void setTime(@NotNull TimeValue time, @NotNull String timeTypeString) {
        timeValue = time;
        timeTypeCombo.setSelectedItem(TimeType.fromStringValue(timeTypeString).stringValue());
        String text = currentSelectedTimeType().asStringFromTime(time);
        waitField.setText(text);
    }
    
    public TimeType currentSelectedTimeType() {
        try {
            String item = (String) timeTypeCombo.getSelectedItem();
            return TimeType.fromStringValue(item);
        } catch (Exception exc) {
            throw new RuntimeException("Invalid time type");
        }
    }
    
    /**
     * Creates new form EditMacroActionWaitPanel
     */
    public EditMacroActionWaitPanel() {
        initComponents();
        setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        waitLabel = new javax.swing.JLabel();
        waitField = new javax.swing.JTextField();
        timeTypeCombo = new javax.swing.JComboBox<>();

        waitLabel.setText("Wait interval");

        waitField.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(waitField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waitLabel)
                    .addComponent(waitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setup()
    {
        DocumentListener listener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                onWaitTimeCallback.perform(waitField.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                onWaitTimeCallback.perform(waitField.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                onWaitTimeCallback.perform(waitField.getText());
            }
        };
        
        waitField.getDocument().addDocumentListener(listener);
        
        for (TimeType t : TimeType.listOfSimpleTypes()) {
            timeTypeCombo.addItem(t.stringValue());
        }
        
        timeTypeCombo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    String selectedType = (String) timeTypeCombo.getSelectedItem();
                    setTime(timeValue, selectedType);
                    
                    TimeType timeType = TimeType.fromStringValue(selectedType);
                    onTimeTypeCallback.perform(timeType);
                } catch (Exception exc) {
                    
                }
            }
        });
    }
    
    private @NotNull TimeValue timeValue = TimeValue.zero();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> timeTypeCombo;
    public javax.swing.JTextField waitField;
    private javax.swing.JLabel waitLabel;
    // End of variables declaration//GEN-END:variables
}
