/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automater.ui.view;

import automater.TextValue;
import automater.utilities.Callback;
import automater.utilities.SimpleCallback;

/**
 *
 * @author Byti
 */
public class EditMacroActionHotkeyPanel extends javax.swing.JPanel {
    // UI callbacks
    public SimpleCallback onHotkeyButtonCallback = SimpleCallback.createDoNothing();
    public Callback<Boolean> onPressCheckCallback = Callback.createDoNothing();

    /**
     * Creates new form EditMacroActionHotkeyPanel
     */
    public EditMacroActionHotkeyPanel() {
        initComponents();
        setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hotkeyButton = new javax.swing.JButton();
        pressCheck = new javax.swing.JCheckBox();
        keyLabel = new javax.swing.JLabel();

        hotkeyButton.setText("Hotkey");
        hotkeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotkeyButtonActionPerformed(evt);
            }
        });

        pressCheck.setText("Press");
        pressCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressCheckActionPerformed(evt);
            }
        });

        keyLabel.setText("Key");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(keyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hotkeyButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pressCheck)))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotkeyButton)
                    .addComponent(keyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pressCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hotkeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotkeyButtonActionPerformed
        onHotkeyButtonCallback.perform();
    }//GEN-LAST:event_hotkeyButtonActionPerformed

    private void pressCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressCheckActionPerformed
        onPressCheckCallback.perform(pressCheck.isSelected());
    }//GEN-LAST:event_pressCheckActionPerformed

    private void setup()
    {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton hotkeyButton;
    public javax.swing.JLabel keyLabel;
    public javax.swing.JCheckBox pressCheck;
    // End of variables declaration//GEN-END:variables
}
