/*
 * Created by Kristiyan Butev.
 * Copyright © 2019 Kristiyan Butev. All rights reserved.
 */
package automater.ui.view;

import automater.TextValue;
import static automater.TextValue.EditAction_ScreenshotTip;
import automater.utilities.Callback;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Byti
 */
public class EditMacroActionScreenshot extends javax.swing.JPanel {

    // UI callbacks
    public Callback.WithParameter<String> onPathChanged = Callback.buildBlankWithParameter();
    /**
     * Creates new form EditMacroActionScreenshot
     */
    public EditMacroActionScreenshot() {
        initComponents();
        setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathField = new javax.swing.JTextField();
        pathLabel = new javax.swing.JLabel();
        tipLabel = new javax.swing.JLabel();

        pathLabel.setText("Path");

        tipLabel.setText("Tip");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pathField, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pathLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tipLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setup() {
        DocumentListener listener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String result = pathField.getText();
                onPathChanged.perform(result);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String result = pathField.getText();
                onPathChanged.perform(result);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                String result = pathField.getText();
                onPathChanged.perform(result);
            }
        };

        pathField.getDocument().addDocumentListener(listener);

        tipLabel.setText(TextValue.getText(EditAction_ScreenshotTip));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField pathField;
    public javax.swing.JLabel pathLabel;
    public javax.swing.JLabel tipLabel;
    // End of variables declaration//GEN-END:variables
}
