/*
 *  Created by Kristiyan Butev.
 *  Copyright © 2024 Kristiyan Butev. All rights reserved.
 */
package automater.ui.view;

import automater.datasource.StandardDescriptionDataSource;
import automater.ui.text.Strings;
import automater.ui.text.TextValue;
import automater.utilities.Callback;
import automater.utilities.Logger;
import java.awt.Component;
import org.jetbrains.annotations.NotNull;

/**
 *
 * @author Kristiyan Butev
 */
public class RecordMacroPanel extends javax.swing.JPanel implements View {

    // UI callbacks
    public Callback.Blank onSwitchToPlayButton = Callback.buildBlank();
    public Callback.Blank onBeginRecordMacroButton = Callback.buildBlank();
    public Callback.Blank onStopRecordMacroButton = Callback.buildBlank();
    public Callback.Blank onSaveMacroButton = Callback.buildBlank();
    
    /**
     * Creates new form RecordMacroPanel
     */
    public RecordMacroPanel() {
        initComponents();
        setup();
    }
    
    // # View
    
    @Override
    public @NotNull Component asComponent() {
        return this;
    }
    
    @Override
    public void reloadData() {
        
    }
    
    private void setup() {
        eventsLabel.setText(TextValue.getText(TextValue.Record_MacroActionListName));

        macroStateLabel.setText(TextValue.getText(TextValue.Record_IdleStatus, startHotkey));

        saveMacroButton.setText(TextValue.getText(TextValue.Record_SaveButton));
        saveMacroButton.setToolTipText(TextValue.getText(TextValue.Record_SaveButtonDisabledTip));

        updateRecordState();
    }
    
    // # Public properties getters/setters
    public boolean isRecording() {
        return _isRecording;
    }

    public void setListDataSource(@NotNull StandardDescriptionDataSource dataSource) {
        macroActionsList.setModel(dataSource);

        scrollToBottom();
    }

    // # Public UI operations
    
    public void willSwitchToPlayWindow() {
        if (_isRecording) {
            Logger.warning(this, "Switching to play screen while recording is not allowed.");
        }
    }
    
    public void enableSaveButton(boolean enabled) {
        saveMacroButton.setEnabled(enabled);
    }

    public void beginRecording() {
        _isRecording = true;
        _recordStartCount++;
        saveMacroButton.setEnabled(false);

        updateRecordState();
    }

    public void endRecording() {
        _isRecording = false;
        saveMacroButton.setEnabled(true);

        updateRecordState();
    }

    public void setHotkeyText(@NotNull String start, @NotNull String stop) {
        startHotkey = start;
        stopHotkey = stop;

        updateRecordState();
    }

    public void scrollToBottom() {
        var sb = macrosList.getVerticalScrollBar();
        sb.setValue(sb.getMaximum());
    }

    // # Private
    private void updateRecordState() {
        if (!_isRecording) {
            macroStateLabel.setText(TextValue.getText(TextValue.Record_IdleStatus, startHotkey));
            
            if (_recordStartCount == 0) {
                recordMacroButton.setText(TextValue.getText(TextValue.Record_BeginRecordingButtonTitle));
            } else {
                recordMacroButton.setText(TextValue.getText(TextValue.Record_RedoRecordingButtonTitle));
            }

            recordMacroButton.setToolTipText(TextValue.getText(TextValue.Record_BeginRecordingButtonTip));
        } else {
            macroStateLabel.setText(TextValue.getText(TextValue.Record_RecordStatus, stopHotkey));
            
            recordMacroButton.setText(TextValue.getText(TextValue.Record_StopRecordingButtonTitle));
            recordMacroButton.setToolTipText(TextValue.getText(TextValue.Record_StopRecordingButtonTip));
        }
    }

    // Private properties
    private boolean _isRecording = false;
    private int _recordStartCount = 0;
    private @NotNull String startHotkey = Strings.DEFAULT_PLAY_OR_STOP_HOTKEY;
    private @NotNull String stopHotkey = Strings.DEFAULT_PLAY_OR_STOP_HOTKEY;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        macrosList = new javax.swing.JScrollPane();
        macroActionsList = new javax.swing.JList<>();
        saveMacroButton = new javax.swing.JButton();
        recordMacroButton = new javax.swing.JButton();
        macroStateLabel = new javax.swing.JLabel();
        eventsLabel = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setResizable(false);

        macrosList.setViewportView(macroActionsList);

        saveMacroButton.setText("Save");
        saveMacroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMacroButtonActionPerformed(evt);
            }
        });

        recordMacroButton.setText("Record");
        recordMacroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordMacroButtonActionPerformed(evt);
            }
        });

        macroStateLabel.setText("Status");

        eventsLabel.setText("Events");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(macrosList)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eventsLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(recordMacroButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveMacroButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(macroStateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eventsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(macrosList, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveMacroButton)
                    .addComponent(recordMacroButton)
                    .addComponent(macroStateLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void recordMacroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordMacroButtonActionPerformed
        if (!isRecording()) {
            beginRecording();
            onBeginRecordMacroButton.perform();
        } else {
            endRecording();
            onStopRecordMacroButton.perform();
        }
    }//GEN-LAST:event_recordMacroButtonActionPerformed

    private void saveMacroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMacroButtonActionPerformed
        onSaveMacroButton.perform();
    }//GEN-LAST:event_saveMacroButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eventsLabel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JList<String> macroActionsList;
    private javax.swing.JLabel macroStateLabel;
    private javax.swing.JScrollPane macrosList;
    private javax.swing.JButton recordMacroButton;
    private javax.swing.JButton saveMacroButton;
    // End of variables declaration//GEN-END:variables
}
