/*
 *  Created by Kristiyan Butev.
 *  Copyright © 2024 Kristiyan Butev. All rights reserved.
 */
package automater.ui.view;

import automater.datasource.MutableEntryDataSource;
import automater.utilities.Callback;
import java.awt.Component;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import automater.model.MutableStorageValue;

/**
 *
 * @author Kristiyan Butev
 */
public class SettingsPanel extends javax.swing.JPanel implements View {
    
    // UI callbacks
    public Callback.Param<MutableStorageValue.Protocol> onEditItem = Callback.buildBlankWithParameter();
    public Callback.Blank onResetAll = Callback.buildBlank();
    
    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
    }
    
    // # Configuration
    
    public void setDataSource(@NotNull MutableEntryDataSource dataSource) {
        this.dataSource = dataSource;
        settingsList.setModel(dataSource);
    }
    
    public void refreshData() {
        settingsList.updateUI();
    }
    
    // # View
    
    @Override
    public Component asComponent() {
        return this;
    }
    
    @Override
    public void reloadData() {
        
    }
    
    private @Nullable MutableEntryDataSource dataSource;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        settingsList = new javax.swing.JList<>();
        resetAllButton = new javax.swing.JButton();

        settingsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        settingsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(settingsList);

        resetAllButton.setText("Reset All");
        resetAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetAllButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resetAllButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetAllButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void settingsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsListMouseClicked
        var index = settingsList.getSelectedIndex();
        
        if (evt.getClickCount() > 1 && dataSource != null) {
            var item = dataSource.getData().get(index);
            onEditItem.perform(item);
        }
    }//GEN-LAST:event_settingsListMouseClicked

    private void resetAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetAllButtonActionPerformed
        onResetAll.perform();
    }//GEN-LAST:event_resetAllButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetAllButton;
    private javax.swing.JList<String> settingsList;
    // End of variables declaration//GEN-END:variables
}
