/*
 *  Created by Kristiyan Butev.
 *  Copyright © 2024 Kristiyan Butev. All rights reserved.
 */
package automater.ui.view;

import automater.datasource.MutableEntryDataSource;
import automater.presenter.MutableEntryPresenter;
import automater.utilities.Callback;
import java.awt.Component;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 *
 * @author Kristiyan Butev
 */
public class SettingsPanel extends javax.swing.JPanel implements View {
    
    // UI callbacks
    public Callback.WithParameter<MutableEntryPresenter.Protocol> onEditItem = Callback.buildBlankWithParameter();
    
    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
    }
    
    // # Configuration
    
    public void setDataSource(@NotNull MutableEntryDataSource dataSource) {
        this.dataSource = dataSource;
        settingsList.setModel(dataSource);
    }
    
    public void refreshData() {
        settingsList.updateUI();
    }
    
    // # View
    
    @Override
    public Component asComponent() {
        return this;
    }
    
    @Override
    public void reloadData() {
        
    }
    
    private @Nullable MutableEntryDataSource dataSource;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        settingsList = new javax.swing.JList<>();

        settingsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        settingsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(settingsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void settingsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsListMouseClicked
        var index = settingsList.getSelectedIndex();
        
        if (evt.getClickCount() > 1 && dataSource != null) {
            var item = dataSource.getData().get(index);
            item.onEdit(this, () -> {
                onEditItem.perform(item);
            });
        }
    }//GEN-LAST:event_settingsListMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> settingsList;
    // End of variables declaration//GEN-END:variables
}
